### PR TITLE
merge master to wasm branch

### PR DESCRIPTION
**Pull request by ousc**
- [ x ] merge master to wasm branch until 5, March(876afdd)
- [ x ] fix memory access out of bounds due to insufficient wasm stack space(c01a40cf)

I wrote some tests using Karma, but I'm not sure whether these tests can be submitted to pikafish's project.
After testing, the single-thread and multi-thread versions of the merged code can be built and work normally.

### CODE REVIEW

**Comment by PikaCat-OuO** [comment]
Emmm, this PR does not contain `[ x ] merge master to wasm branch until 5, March`?

**Comment by ousc** [comment]
> Emmm, this PR does not contain `[ x ] merge master to wasm branch until 5, March`?

I missed some commit push

**Comment by PikaCat-OuO** [comment]
> I wrote some tests using Karma, but I'm not sure whether these tests can be submitted to pikafish's project. After testing, the single-thread and multi-thread versions of the merged code can be built and work normally.

I think this is the right place to place the tests: https://github.com/official-pikafish/Pikafish/tree/wasm/tests
Anyway, it looks good to me, so I just merge it now.

**Comment by ousc** [comment]
In fact, I'm not sure whether the existing test can provide tests for wasm.

**Pull request merged**
